# Change these first
owner: nathan026
repo: Upptime

# Add your sites here
sites:
  - name: ezimanager.gapsolutions.com.au
    url: https://ezimanager.gapsolutions.com.au
  - name: login.ezimanager.cloud
    url: https://login.ezimanager.cloud
  - name: express.ezimanager.cloud
    url: https://express.ezimanager.cloud
  - name: gap4.ezimanager.cloud
    url: https://gap4.ezimanager.cloud
  - name: metcash.gapsolutions.com.au
    url: https://metcash.ezimanager.cloud
  - name: au2.ezimanager.cloud
    url: https://au2.ezimanager.cloud
  - name: au3.ezimanager.cloud
    url: https://au3.ezimanager.cloud
  - name: ezi-rewards.net
    url: https://ezirewards.net/


status-website:
  theme: light
  baseUrl: /Upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EMC Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /Upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
